### ISSUE TITLE
GATEWAY - Have to hit ENTER twice after leaving a BBS

### ISSUE THREAD

**Issue by plbyrd** [sharpninja/WorldBankBBS#2]
When you are disconnected by the BBS remotely, you have to hit ENTER twice to get the BBS prompt to show up.

**Comment by sharpninja** [comment]
This cannot be avoided.  The root cause is described in the "partially open" problem as seen here:

http://www.codeproject.com/Articles/37490/Detection-of-Half-Open-Dropped-TCP-IP-Socket-Conne

The solutions provided are not feasible because the keep alive messages sent to a bbs would be interpreted as input since the BBS doesn't know anything about what's going on in a RAW connection.
